[project]
name = "vr-foraging-replenishment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aind-behavior-vr-foraging[data]>=1.2.6",
    "aind-behavior-vr-foraging-curricula>=1.2.6",
    "aind-behavior-services == 0.13.7",
    "marimo[recommended]>=0.24.0",
    "matplotlib>=3.11.1",
]
